sudo: required

language: python
python:
  - "2.7"

before_install:
  - mkdir -p tests/data
  - wget -qO- http://quast.bioinf.spbau.ru/static/chr21.tar.gz | tar xvz -C tests/data
  - wget -qO- http://quast.bioinf.spbau.ru/static/bwa.tar.gz | tar xvz -C tests/data
  - pip install --upgrade setuptools pip

install:
  - python setup.py install

script:
  - nosetests --nocapture tests:TravisTests

notifications:
  on_success: always
  email: false
  slack: astrazeneca-ngs:cP6TAiGMYU857H0Vahc42SHD
