{% set version=load_setup_py_data().get('version') }}

package:
  name: targqc
  version: {{ version }}

source:
  git_url: https://github.com/vladsaveliev/TargQC
  git_rev: master

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - setuptools >=18.5
    - numpy
  run:
    - python
    - qualimap
    - sambamba
    - htslib ==1.3
    - bwa
    - bedtools
    - cython
    # pip packages:
    - numpy
    - tempita
    - pandas
    - pybedtools
    - gffutils
    - nose
    - pysam
    - ngs_utils

test:
  # Python imports
  imports:
    - targqc
    - ensembl
    - bed_annotation

  commands:
    - targqc --version

about:
  home: https://github.com/vladsaveliev/TargQC
  license: GNU General Public License v3 (GPLv3)
  summary: 'Target capture coverage QC'
  license_family: GPL3
