{% set version=load_setup_py_data().get('version') %}

package:
  name: targqc
  version: "{{ version }}"

source:
  git_url: https://github.com/vladsaveliev/TargQC
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python >=3.6
    - numpy
    - six
  run:
    - python >=3.6
    - six
    - qualimap
    - sambamba
    - bedtools >=2.25
    - pybedtools
    - nose
    - cython
    - numpy
    - joblib
    - gffutils
    - beautifulsoup4
    - lxml
    - xlsxwriter >=0.5.5
    - natsort

test:
  imports:
   - targqc
   - ensembl

  commands:
   - targqc --version

about:
  home: https://github.com/vladsaveliev/TargQC
  license: GNU General Public License v3 (GPLv3)
  summary: 'Target capture coverage QC'
  license_family: GPL3

