{% set version=load_setup_py_data().get('version') %}

package:
  name: targqc
  version: "{{ version }}"

source:
  git_url: https://github.com/vladsaveliev/TargQC
  git_rev: master

build:
  number: 0

test:
  imports:
   - targqc
   - ensembl

  commands:
   - targqc --version

about:
  home: https://github.com/vladsaveliev/TargQC
  license: GNU General Public License v3 (GPLv3)
  summary: 'Target capture coverage QC'
  license_family: GPL3

requirements:
  build:
    - python ==3.6
    - numpy
    - ngs_utils
  run:
    - python ==3.6
    - six
    - qualimap
    - sambamba ==0.6.6  # having issues with 0.6.8 https://github.com/vladsaveliev/TargQC/issues/5#issuecomment-433388616
    - bedtools >=2.25
    - pybedtools
    - nose
    - cython
    - numpy
    - joblib
    - gffutils
    - beautifulsoup4
    - lxml
    - xlsxwriter >=0.5.5
    - natsort
    - click
    - ngs_utils
