{% set version=load_setup_py_data().get('version') %}

package:
  name: targqc
  version: "{{ version }}"

source:
  git_url: https://github.com/vladsaveliev/TargQC
  git_rev: master

build:
  number: 3

requirements:
  build:
    - python
    - numpy
    - ngs_utils
  run:
    - python
    - six
    - qualimap
    - sambamba
    - bwa
    - bedtools >=2.25
    - pybedtools
    - nose
    - ngs_utils

test:
  imports:
   - targqc
   - ensembl

  commands:
   - targqc --version

about:
  home: https://github.com/vladsaveliev/TargQC
  license: GNU General Public License v3 (GPLv3)
  summary: 'Target capture coverage QC'
  license_family: GPL3

